Repository DEPthes/3rd-MVP-NoPlanB-Server, pull requests merged in 2024-08, with the labels that each got.

#12 [FEAT] S3설정
  .gitignore
  build.gradle
  src/main/java/com/noplanb/domain/s3/application/AwsFileService.java
  src/main/java/com/noplanb/global/config/S3Config.java
Labels: ✨ feature

#17 퀘스트 수정,삭제, 조회 로직
  .gitignore
  src/main/java/com/noplanb/domain/character/domain/Character.java
  src/main/java/com/noplanb/domain/quest/application/CalendarService.java
  src/main/java/com/noplanb/domain/quest/application/QuestService.java
  src/main/java/com/noplanb/domain/quest/controller/CalendarController.java
  src/main/java/com/noplanb/domain/quest/controller/QuestController.java
  src/main/java/com/noplanb/domain/quest/domain/Quest.java
  src/main/java/com/noplanb/domain/quest/dto/req/CreateQuestReq.java
  src/main/java/com/noplanb/domain/quest/dto/req/ModifyQuestReq.java
  src/main/java/com/noplanb/domain/quest/dto/res/RetrieveCalendarRes.java
  src/main/java/com/noplanb/domain/quest/dto/res/RetrieveLevelAndTodayExpRes.java
  src/main/java/com/noplanb/domain/quest/dto/res/RetrieveQuestRes.java
  src/main/java/com/noplanb/global/payload/ErrorCode.java
  src/main/java/com/noplanb/global/payload/exception/QuestNotFoundException.java
Labels: ✨ feature

#20 달력조회 api
  .gitignore
  src/main/java/com/noplanb/domain/character/domain/Character.java
  src/main/java/com/noplanb/domain/quest/application/CalendarService.java
  src/main/java/com/noplanb/domain/quest/application/QuestService.java
  src/main/java/com/noplanb/domain/quest/controller/CalendarController.java
  src/main/java/com/noplanb/domain/quest/domain/DailyExperience.java
  src/main/java/com/noplanb/domain/quest/dto/res/RetrieveCalendarRes.java
  src/main/java/com/noplanb/domain/quest/repository/DailyExperienceRepository.java
Labels: ✨ feature

#18 로그인/캐릭터 관련 기능 수정사항 반영
  build.gradle
  src/main/java/com/noplanb/NoPlanBApplication.java
  src/main/java/com/noplanb/domain/auth/application/AuthService.java
  src/main/java/com/noplanb/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/noplanb/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/noplanb/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/noplanb/domain/auth/controller/AuthController.java
  src/main/java/com/noplanb/domain/auth/domain/Token.java
  src/main/java/com/noplanb/domain/auth/dto/request/SigninReq.java
  src/main/java/com/noplanb/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/noplanb/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/noplanb/domain/auth/repository/TokenRepository.java
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
  src/main/java/com/noplanb/domain/character/domain/Character.java
  src/main/java/com/noplanb/domain/character/dto/request/UpdateNameReq.java
  src/main/java/com/noplanb/domain/character/dto/response/MyCharacterInfoRes.java
  src/main/java/com/noplanb/domain/character/dto/response/MyCharaterDetailRes.java
  src/main/java/com/noplanb/domain/character/dto/response/MyCharaterListRes.java
  src/main/java/com/noplanb/domain/character/repository/CharacterRepository.java
  src/main/java/com/noplanb/domain/item/domain/Item.java
  src/main/java/com/noplanb/domain/item/domain/ItemStatus.java
  src/main/java/com/noplanb/domain/item/domain/ItemType.java
  src/main/java/com/noplanb/domain/item/repository/ItemRepository.java
  src/main/java/com/noplanb/domain/item_image/domain/ItemImage.java
  src/main/java/com/noplanb/domain/item_image/domain/repository/ItemImageRepository.java
  src/main/java/com/noplanb/domain/user/application/UserService.java
  src/main/java/com/noplanb/domain/user/domain/Provider.java
  src/main/java/com/noplanb/domain/user/domain/Role.java
  src/main/java/com/noplanb/domain/user/domain/User.java
  src/main/java/com/noplanb/domain/user/repository/UserRepository.java
  src/main/java/com/noplanb/global/DefaultAssert.java
  src/main/java/com/noplanb/global/config/AppConfig.java
  src/main/java/com/noplanb/global/config/YamlPropertySourceFactory.java
  src/main/java/com/noplanb/global/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/noplanb/global/config/security/CustomOncePerRequestFilter.java
  src/main/java/com/noplanb/global/config/security/OAuth2Config.java
  src/main/java/com/noplanb/global/config/security/SecurityConfig.java
  src/main/java/com/noplanb/global/config/security/auth/OAuth2UserInfo.java
  src/main/java/com/noplanb/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/noplanb/global/config/security/auth/company/Kakao.java
  src/main/java/com/noplanb/global/config/security/token/CurrentUser.java
  src/main/java/com/noplanb/global/config/security/token/UserPrincipal.java
  src/main/java/com/noplanb/global/config/security/util/JwtTokenUtil.java
  src/main/java/com/noplanb/global/error/DefaultAuthenticationException.java
  src/main/java/com/noplanb/global/error/DefaultException.java
  src/main/java/com/noplanb/global/payload/ErrorCode.java
  src/main/java/com/noplanb/global/payload/ErrorResponse.java
Labels: refactor

#26 사용자 계정 조회 및 카테고리별 아이템 목록 조회 기능 구현
  src/main/java/com/noplanb/domain/auth/application/AuthService.java
  src/main/java/com/noplanb/domain/auth/controller/AuthController.java
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
  src/main/java/com/noplanb/domain/item/application/ItemService.java
  src/main/java/com/noplanb/domain/item/controller/ItemController.java
  src/main/java/com/noplanb/domain/item/domain/Item.java
  src/main/java/com/noplanb/domain/item/domain/ItemStatus.java
  src/main/java/com/noplanb/domain/item/domain/ItemType.java
  src/main/java/com/noplanb/domain/item/dto/response/CategoryItemListRes.java
  src/main/java/com/noplanb/domain/item/dto/response/CategoryItemRes.java
  src/main/java/com/noplanb/domain/user/application/UserService.java
  src/main/java/com/noplanb/domain/user/controller/UserController.java
  src/main/java/com/noplanb/domain/user/dto/response/MyAccountRes.java
Labels: ✨ feature

#34 초기 캐릭터 생성 기능 구현
  src/main/java/com/noplanb/domain/auth/controller/AuthController.java
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
  src/main/java/com/noplanb/domain/item/controller/ItemController.java
  src/main/java/com/noplanb/domain/quest/controller/CalendarController.java
  src/main/java/com/noplanb/domain/quest/controller/QuestController.java
  src/main/java/com/noplanb/domain/user/controller/UserController.java
Labels: 📄 docs, ☁️ enhancement, ✨ feature

#38 아이템 장착 기능 구현
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
  src/main/java/com/noplanb/domain/character/dto/request/MyCharacterEquipItemDetailReq.java
  src/main/java/com/noplanb/domain/character/dto/request/MyCharacterEquipItemReq.java
Labels: ✨ feature

#43 캐릭터 아이템 장착 기능 수정
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
Labels: ⚒️ fix

#44 @Transaction 어노테이션 추가
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
Labels: ⚒️ fix

#45 캐릭터 정보 응답값 수정
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/dto/response/MyCharaterDetailRes.java
Labels: ⚒️ fix

#46 캐릭터 존재 여부 확인 기능 구현
  src/main/java/com/noplanb/domain/character/repository/CharacterRepository.java
  src/main/java/com/noplanb/domain/user/application/UserService.java
  src/main/java/com/noplanb/domain/user/controller/UserController.java
  src/main/java/com/noplanb/domain/user/dto/response/UserCharacterExistRes.java
Labels: ✨ feature

#49 [REFACTOR] 오늘 만든 퀘스트들의 경험치 넘겨주기 로직 추가
  src/main/java/com/noplanb/domain/quest/application/QuestService.java
  src/main/java/com/noplanb/domain/quest/dto/res/RetrieveLevelAndTodayExpRes.java
  src/main/java/com/noplanb/domain/quest/repository/QuestRepository.java
Labels: refactor

#50 [FEAT] 캐릭터 레벨,경험치,당일퀘스트 초기화 API 완성
  src/main/java/com/noplanb/domain/character/application/CharacterService.java
  src/main/java/com/noplanb/domain/character/controller/CharacterController.java
  src/main/java/com/noplanb/domain/character/domain/Character.java
  src/main/java/com/noplanb/domain/quest/repository/QuestRepository.java
Labels: ✨ feature

#51 패션 아이템 삭제를 위한 enum 추가
  src/main/java/com/noplanb/domain/item/application/ItemService.java
  src/main/java/com/noplanb/domain/item_image/domain/ItemType.java
Labels: ☁️ enhancement

#52 회원 탈퇴 기능 구현
  src/main/java/com/noplanb/domain/auth/repository/TokenRepository.java
  src/main/java/com/noplanb/domain/character/domain/Character.java
  src/main/java/com/noplanb/domain/character/repository/CharacterRepository.java
  src/main/java/com/noplanb/domain/user/application/UserService.java
  src/main/java/com/noplanb/domain/user/controller/UserController.java
Labels: ✨ feature

#54 API url 수정
  src/main/java/com/noplanb/domain/user/controller/UserController.java
Labels: 📄 docs
